UPDATE CITY_NORMALIZED cn
SET NORMALIZED_STATE_ID = (
    SELECT s.STATE_ID
    FROM STATE s
    WHERE s.STATE = cn.STATE_NAME
)
WHERE EXISTS (
    SELECT 1
    FROM STATE s
    WHERE s.STATE = cn.STATE_NAME
);
